spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
    open-in-view: 'false'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    url:
      jdbc :mysql://localhost:3306/money_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    init-sqls:
      - CREATE SCHEMA IF NOT EXISTS money_app;
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
    springframework:
        security: DEBUG
server:
  port: 8080


