spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: 'false'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/money-app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
    springframework:
        security: DEBUG
server:
  port: 8080
#rsa:
#  private-key: classpath:certs/private.pem #see if there's an issue
#  public-key: classpath:certs/public.pem #see if there's an issue


